scoping error:
  $ dune exec miniml2wasm -- scope_1.mml
  typing ...
  scope analysing ...
  ident: y not found in env.locals
  $ dune exec miniml2wasm -- scope_2.mml
  typing ...
  scope analysing ...
  ident: y not found in env.locals
