scoping error:
  $ dune exec miniml2wasm -- scope_1.mml
  scope analysing ...
  ident: y not found in env.locals
  $ dune exec miniml2wasm -- scope_2.mml
  scope analysing ...
  ident: y not found in env.locals
  $ dune exec miniml2wasm -- scope_3.mml
  scope analysing ...
  ident: y not found in env.locals
  $ dune exec miniml2wasm -- scope_4.mml
  scope analysing ...
  ident: y not found in env.locals
