typing error:
  $ dune exec miniml2wasm -- typer_1.mml
  typing ...
  Typing error: File "typer_1.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- typer_2.mml
  typing ...
  Typing error: File "typer_2.mml", line 1, char 14: attempt to perform binop 'add' on a non i32 types
  $ dune exec miniml2wasm -- typer_3.mml
  typing ...
  Typing error: File "typer_3.mml", line 1, char 15: attempt to perform unop '-' on a non i32 type
  $ dune exec miniml2wasm -- typer_4.mml
  typing ...
  Typing error: File "typer_4.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- typer_5.mml
  typing ...
  Typing error: File "typer_5.mml", line 4, char 3: unit type expected in the left-hand side of a sequence
  $ dune exec miniml2wasm -- typer_6.mml
  typing ...
  Typing error: File "typer_6.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- typer_7.mml
  typing ...
  Typing error: File "typer_7.mml", line 3, char 2: type bool is expected in the condition of a while-loop
  $ dune exec miniml2wasm -- typer_8.mml
  typing ...
  Typing error: File "typer_8.mml", line 3, char 2: type unit is expected in the body of a while-loop
