typing list error:
  $ dune exec miniml2wasm -- list_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_1.mml", line 1, char 8: attempt to perform a cons operation with a non supported type (unit)
  $ dune exec miniml2wasm -- list_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_2.mml", line 1, char 8: attempt to perform a cons operation on a non list var
  $ dune exec miniml2wasm -- list_3.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_3.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- list_4.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_4.mml", line 2, char 8: attempt to perform a cons operation with different types
  $ dune exec miniml2wasm -- list_empty_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_empty_1.mml", line 1, char 0: attempt to perform a list_empty operation on a non list var
  $ dune exec miniml2wasm -- list_empty_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_empty_2.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- list_hd_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_hd_1.mml", line 1, char 0: attempt to perform a list_hd operation on a non list var
  $ dune exec miniml2wasm -- list_hd_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_hd_2.mml", line 1, char 0: attempt to perform a list_hd operation on a non typed list or an empty list
  $ dune exec miniml2wasm -- list_hd_3.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_hd_3.mml", line 2, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- list_tl_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_tl_1.mml", line 1, char 0: attempt to perform a list_tl operation on a non list var
  $ dune exec miniml2wasm -- list_tl_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_tl_2.mml", line 1, char 0: attempt to perform a list_tl operation on a non typed list or an empty list
  $ dune exec miniml2wasm -- list_tl_3.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_tl_3.mml", line 2, char 0: attempt to perform an assignment with different types
