typing list error:
  $ dune exec miniml2wasm -- list_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_1.mml", line 1, char 8: attempt to perform a cons operation with a non supported type (unit)
  $ dune exec miniml2wasm -- list_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_2.mml", line 1, char 8: attempt to perform a cons operation a non list var
  $ dune exec miniml2wasm -- list_3.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_3.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- list_4.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "list_4.mml", line 2, char 8: attempt to perform a cons operation with different types
