typing matrix_make error:
  $ dune exec miniml2wasm -- matrix_make_0.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "matrix_make_0.mml", line 1, char 23: attempt to perform an array_make with non supported type
  $ dune exec miniml2wasm -- matrix_make_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "matrix_make_1.mml", line 1, char 10: attempt to perform a x or y zero-size matrix_make
  $ dune exec miniml2wasm -- matrix_make_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "matrix_make_2.mml", line 1, char 10: attempt to perform a matrix_make with a non i32 type size
  $ dune exec miniml2wasm -- matrix_make_3.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "matrix_make_3.mml", line 1, char 26: attempt to perform a matrix_make with non supported type
  $ dune exec miniml2wasm -- matrix_make_4.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "matrix_make_4.mml", line 1, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- matrix_make_5.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "matrix_make_5.mml", line 1, char 0: attempt to perform an assignment with different types
