typing array error:
  $ dune exec miniml2wasm -- array_access_indice.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_access_indice.mml", line 3, char 2: attempt to perform an array access with a non i32 indice
  $ dune exec miniml2wasm -- array_global.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_global.mml", line 8, char 2: attempt to perform an array access with a non i32 indice
  $ dune exec miniml2wasm -- array_matrix_typ_uniform_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_matrix_typ_uniform_1.mml", line 1, char 10: attempt to init an array with non supported/uniform types
  $ dune exec miniml2wasm -- array_matrix_typ_uniform_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_matrix_typ_uniform_2.mml", line 1, char 10: attempt to init an array with non supported/uniform types
  $ dune exec miniml2wasm -- array_matrix_typ_uniform_3.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_matrix_typ_uniform_3.mml", line 1, char 11: attempt to init an array with non supported/uniform types
  $ dune exec miniml2wasm -- array_ref.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_ref.mml", line 9, char 4: attempt to perform an array assignment with different types
  $ dune exec miniml2wasm -- array_size_0.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_size_0.mml", line 1, char 10: attempt to init a zero-size array
  $ dune exec miniml2wasm -- array_size_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_size_1.mml", line 3, char 2: attempt to perform an array_size call on a non array var
  $ dune exec miniml2wasm -- array_size_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_size_2.mml", line 3, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- array_typ_size.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_typ_size.mml", line 2, char 0: attempt to perform an assignment with different types
  $ dune exec miniml2wasm -- array_typ_uniform_1.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_typ_uniform_1.mml", line 2, char 19: attempt to init an array with non supported/uniform types
  $ dune exec miniml2wasm -- array_typ_uniform_2.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_typ_uniform_2.mml", line 2, char 10: attempt to init an array with non supported/uniform types
  $ dune exec miniml2wasm -- array_var.mml
  parsing ...
  scope analysing ...
  typechecking ...
  Typechecking error: File "array_var.mml", line 4, char 2: attempt to perform an array access on a non array var
