export js:
  $ dune exec miniml2wasm -- export.mml
  parsing ...
  scope analysing ...
  typechecking ...
  compiling ...
  compilation target file _wasm/export.wasm: done!
  $ deno run --allow-read export.js
  Export function call: double
  42
