factorial:
  $ dune exec miniml2wasm -- fact.mml
  parsing ...
  scope analysing ...
  typechecking ...
  compiling ...
  compilation target file _wasm/fact.wasm: done!
  $ wasm -d _wasm/fact.wasm -o _wasm/fact.wat
  $ owi _wasm/fact.wat
  function 2function 1function 0
