fibonacci:
  $ dune exec miniml2wasm -- fibo.mml
  parsing ...
  scope analysing ...
  typechecking ...
  compiling ...
  compilation target file _wasm/fibo.wasm: done!
  $ wasm -d _wasm/fibo.wasm -o _wasm/fibo.wat
  $ owi _wasm/fibo.wat
  function 1function 0
