print js call:
  $ dune exec miniml2wasm -- print.mml
  parsing ...
  scope analysing ...
  typechecking ...
  compiling ...
  compilation target file _wasm/print.wasm: done!
  $ deno run --allow-read print.js
  Define host function: print_i32
  42
