scoping error:
  $ dune exec miniml2wasm -- block_1.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- block_2.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- block_3.mml
  parsing ...
  scope analysing ...
  ident: x not found or not in current scope
  $ dune exec miniml2wasm -- global_1.mml
  parsing ...
  scope analysing ...
  ident: func already exists in global scope
  $ dune exec miniml2wasm -- global_2.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- let.mml
  parsing ...
  scope analysing ...
  ident: x not found or not in current scope
  $ dune exec miniml2wasm -- ref.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- var.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
