scoping error:
  $ dune exec miniml2wasm -- scope_1.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- scope_2.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- scope_3.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- scope_4.mml
  parsing ...
  scope analysing ...
  ident: x not found or not in current scope
  $ dune exec miniml2wasm -- scope_5.mml
  parsing ...
  scope analysing ...
  ident: x not found or not in current scope
  $ dune exec miniml2wasm -- scope_6.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
  $ dune exec miniml2wasm -- scope_7.mml
  parsing ...
  scope analysing ...
  ident: y not found or not in current scope
